#/atotrukis_hello_world:
#    path:     /
#    defaults: { _controller: AtotrukisMainBundle:Default:index }

create_event:
    path:     /mano-renginiai/sukurti
    defaults: { _controller: AtotrukisMainBundle:Event:create }

edit_event:
    path:     /mano-renginiai/redaguoti/{id}
    defaults: { _controller: AtotrukisMainBundle:Event:editMyEvent }

delete_event:
    path:     /mano-renginiai/istrinti/{id}
    defaults: { _controller: AtotrukisMainBundle:Event:deleteMyEvent }


my_events:
    path:     /mano-renginiai
    defaults: { _controller: AtotrukisMainBundle:Event:readMyEvents }




_show_all_events:
    path:     /
    defaults: { _controller: AtotrukisMainBundle:ShowEvents:ShowAllEvents }

_show_event:
    path:     renginys/{id}
    defaults: { _controller: AtotrukisMainBundle:ShowEvents:ShowEvent }
