atotrukis_hello_world:
    path:     /
    defaults: { _controller: AtotrukisMainBundle:Default:index }

create_event:
    path:     /mano-renginiai/sukurti
    defaults: { _controller: AtotrukisMainBundle:Event:createEvent }

edit_event:
    path:     /mano-renginiai/redaguoti/{id}
    defaults: { _controller: AtotrukisMainBundle:Event:editMyEvent }

delete_event:
    path:     /mano-renginiai/istrinti/{id}
    defaults: { _controller: AtotrukisMainBundle:Event:deleteMyEvent }

my_events:
    path:     /mano-renginiai
    defaults: { _controller: AtotrukisMainBundle:Event:readUserEvents }

one_event:
    path:     /mano-renginiai/renginys/{id}
    defaults: { _controller: AtotrukisMainBundle:Event:getEvent }

search_results:
    path:     /search
    defaults: { _controller: AtotrukisMainBundle:Event:getSearchResult }


