atotrukis_hello_world:
    path:     /
    defaults: { _controller: AtotrukisMainBundle:Default:index }

create_event:
    path:     /mano-renginiai/sukurti
    defaults: { _controller: AtotrukisMainBundle:Event:createEvent }

edit_event:
    path:     /mano-renginiai/redaguoti/{eventId}
    defaults: { _controller: AtotrukisMainBundle:Event:editMyEvent }

delete_event:
    path:     /mano-renginiai/istrinti/{eventId}
    defaults: { _controller: AtotrukisMainBundle:Event:deleteMyEvent }

my_events:
    path:     /mano-renginiai
    defaults: { _controller: AtotrukisMainBundle:Event:readUserEvents }

one_event:
    path:     /mano-renginiai/renginys/{id}
    defaults: { _controller: AtotrukisMainBundle:Event:getEvent }

search_results:
    path:     /search
    defaults: { _controller: AtotrukisMainBundle:Event:getSearchResult }



_show_event:
    path:     renginys/{eventId}
    defaults: { _controller: AtotrukisMainBundle:Default:showEvent }

quiz:
    path:     /apklausa
    defaults: { _controller: AtotrukisMainBundle:Quiz:quiz }

admin_users:
  path:       /admin/users
  defaults: { _controller: AtotrukisMainBundle:Admin:readUsers}

admin_user_block:
  path:       /admin/vartotojai/block/{id}
  defaults: { _controller: AtotrukisMainBundle:Admin:blockUser}

attend_event:
    path:     /attend
    defaults: { _controller: AtotrukisMainBundle:Event:attend }
    methods:  [POST]

leave_event:
    path:     /leave
    defaults: { _controller: AtotrukisMainBundle:Event:leave }
    methods:  [POST]

attend_event_sml:
    path:     /attendSml
    defaults: { _controller: AtotrukisMainBundle:Event:attendSmall }
    methods:  [POST]

leave_event_sml:
    path:     /leaveSml
    defaults: { _controller: AtotrukisMainBundle:Event:leaveSmall }
    methods:  [POST]

get_news:
    pattern:   /news
    defaults:  { _controller: AtotrukisMainBundle:Event:getNewestEvents }

comment_form:
    pattern:   /commentForm
    defaults:  { _controller: AtotrukisMainBundle:Comments:createComment }