parameters:
    my_user_provider.class: Atotrukis\MainBundle\Service\FOSUBUserProvider

services:
    atotrukis_user.registration.form.type:
        class: Atotrukis\MainBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: atotrukis_user_registration }

    atotrukis_comments.form.type.createCommentForm:
        class: Atotrukis\MainBundle\Form\Type\CreateCommentFormType
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: createCommentForm }

    eventService:
        class: Atotrukis\MainBundle\Service\EventService
        arguments: [ @doctrine.orm.entity_manager ]

    adminService:
        class: Atotrukis\MainBundle\Service\AdminService
        arguments: [ @doctrine.orm.entity_manager, @service_container, @eventService ]

    userKeywordService:
        class: Atotrukis\MainBundle\Service\UserKeywordService
        arguments: [ @doctrine.orm.entity_manager, @service_container ]

    cityService:
      class: Atotrukis\MainBundle\Service\CityService
      arguments: [@doctrine.orm.entity_manager]

    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id}, @userKeywordService,  @cityService ]

    dateFormatService:
      class: Atotrukis\MainBundle\Service\DateFormatService
      arguments: []

    homePageService:
      class: Atotrukis\MainBundle\Service\HomePageService
      arguments: [ @doctrine.orm.entity_manager, @request_stack, @security.context, @eventService, @userKeywordService, @searchService ]

    searchService:
      class: Atotrukis\MainBundle\Service\SearchService
      arguments: [@doctrine.orm.entity_manager, @templating, @eventService, @userKeywordService]

    commentsService:
      class: Atotrukis\MainBundle\Service\CommentsService
      arguments: [@doctrine.orm.entity_manager, @eventService, @templating]

    atotrukis_search.form.type.createCommentForm:
        class: Atotrukis\MainBundle\Form\Type\SearchFormType
        arguments: [ @router ]
        tags:
            - { name: form.type, alias: searchForm }

    Atotrukis_user.registration:
            class: Atotrukis\MainBundle\EventListener\RegistrationListener
            arguments: [@router]
            tags:
                - { name: kernel.event_subscriber }

