services:
    atotrukis_user.registration.form.type:
        class: Atotrukis\MainBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: atotrukis_user_registration }

    eventService:
        class: Atotrukis\MainBundle\Service\EventService
        arguments: [ @doctrine.orm.entity_manager ]

    eventService:
        class: Atotrukis\MainBundle\Service\UserKeywordService
        arguments: [ @doctrine.orm.entity_manager ]