imports:
    - php

tools:
    # PHP
    php_sim:                true
    php_code_sniffer:       true
    php_cs_fixer:           true
    php_hhvm:               true
    php_mess_detector:      true
    php_pdepend:            true
    php_loc:                true
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled:    true

    # JS
    js_hint: true

filter:
    excluded_paths:
        - app/*
        - src/**/spec/*
        - src/**/DataFixtures/**/*
        - web/javascripts/bootstrap.js
        - web/javascripts/bootstrap/*

changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b"]
